### ISSUE TITLE
When will the servers be restored?

### ISSUE THREAD

**Issue by ghost** [PenguinMod/penguinmod.github.io#13]
I don't know why the servers shut down. Could you please answer and restore them as soon as you can?

**Comment by RedMan13** [comment]
> I don't know why the servers shut down. Could you please answer and restore them as soon as you can?

it says on the discord server

**Comment by ghost** [comment]
I can't access Discord. Could you say that comment which says that?

**Comment by RedMan13** [comment]
> I can't access Discord. Could you say that comment which says that?

> ❌ **-** Project Sharing is *not* possible at the moment, we have officially **ran out of storage space** on our server
> - We are working on solutions to the problem but this could take a while to be fully resolved for the future

as of this notice the api will be down until further notice

**Comment by ghost** [comment]
OK.
