### ISSUE TITLE
it doesn't work when compiled with githpod and running on win32

### ISSUE THREAD

**Issue by WINRARisyou** [PenguinMod/penguinmod.github.io#14]
### Expected Behavior
PenguinMod should run after being compiled with no issues 

### Actual Behavior
PenguinMod compiles successfully, but when running, it crashes:
![image](https://github.com/PenguinMod/penguinmod.github.io/assets/99762912/6fed579a-8da9-45fe-a25b-103199c23266)

### Steps to Reproduce

try compiling it in gitpod. it either wont work or will compile and crash upon running.

### Operating System and Browser

I used gitpod to compile it which is is linux but i ran it on win32 firefox. it may work on a more powerful machine but i cant test it rn so it might get updated tomorrow

**Comment by WINRARisyou** [comment]
it used to work with gitpod aswell back in late 2022 i think

**Comment by RedMan13** [comment]
> ### Expected Behavior
> 
> PenguinMod should run after being compiled with no issues
> ### Actual Behavior
> 
> PenguinMod compiles successfully, but when running, it crashes: ![image](https://user-images.githubusercontent.com/99762912/262212980-6fed579a-8da9-45fe-a25b-103199c23266.png)
> ### Steps to Reproduce
> 
> try compiling it in gitpod. it either wont work or will compile and crash upon running.
> ### Operating System and Browser
> 
> I used gitpod to compile it which is is linux but i ran it on win32 firefox. it may work on a more powerful machine but i cant test it rn so it might get updated tomorrow

iirc this is because vm is outdated or not installed or some form of that
this happens in development to if you dont install everything then link vm

**Comment by WINRARisyou** [comment]
it worked when i linked the vm lol
