### ISSUE TITLE
Better name

### ISSUE THREAD

**Issue by GalacticCoderReturns** [PenguinMod/penguinmod.github.io#19]
I think we should abandon the 9 month old name of PenguinMod for a better name, PenguinProgram! 
Reasons I think this name is better:
It represents more about what it is. For example, if someone came to the website, unintroduced to Scratch, they would think it is a website for the Minecraft mod Penguin Mod, or think it is just a simple modification of something. The new name lets people know it is a programming language.
The words Penguin and Program have the same syllables and first letter.

**Comment by RedMan13** [comment]
nah

**Comment by GalacticCoderReturns** [comment]
Seriously??? Just a NOPE?

**Comment by RedMan13** [comment]
> Seriously??? Just a NOPE?

we dont normally fluff up responses :/

**Comment by RedMan13** [comment]
a more formal response that i thought of would be 

> after careful consideration, we have decided to __reject__ your suggestion. as we think that "PenguinProject" does not fit the app

**Comment by JeremyGamer13** [comment]
i dont think a name change would be a good idea, penguinmod is easy to say and its already the name everyone knows it by & renaming would be a lot of things to change in the app

**Comment by polygoners1** [comment]
> i dont think a name change would be a good idea, penguinmod is easy to say and its already the name everyone knows it by & renaming would be a lot of things to change in the app

and also the acronym would be "PP"
"new extension!!! "PP VR" put penguinprogam onto YOUR OWN VR headset!!!"
like... really?

**Comment by Ianyourgod** [comment]
you are half a year late, your input is not needed
