### ISSUE TITLE
How do you change the file searcher?

### ISSUE THREAD

**Issue by GalacticCoderReturns** [PenguinMod/penguinmod.github.io#20]
I'm making a PenguinMod mod and I want when you load a project from your computer, the file finder says "Zinc Coding program", but it says "PenguinMod Project". How is that managed?

**Comment by JeremyGamer13** [comment]
that seems to be handled by `src/lib/tw-filesystem-api.js`
https://github.com/PenguinMod/penguinmod.github.io/blob/develop/src/lib/tw-filesystem-api.js

**Comment by GalacticCoderReturns** [comment]
I mean this
![Screenshot 2023-09-10 4 29 02 PM](https://github.com/PenguinMod/penguinmod.github.io/assets/142676627/9407df64-fc49-48ad-87a5-6e13c46792cf)

**Comment by JeremyGamer13** [comment]
yes, that file contains the code to change that label

**Comment by GalacticCoderReturns** [comment]
But where?

**Comment by JeremyGamer13** [comment]
line 7 and 21? if you changed those already and nothing happened, do note that pm takes around 5 minutes to update usually

**Comment by GalacticCoderReturns** [comment]
Thank you! It did not work last time I tried.
