### ISSUE TITLE
How to you do this?

### ISSUE THREAD

**Issue by GalacticCoderReturns** [PenguinMod/penguinmod.github.io#23]
![image](https://github.com/PenguinMod/penguinmod.github.io/assets/142676627/b89701ac-f2bd-48d1-92c8-0f2d92de2f96)

**Comment by GalacticCoderReturns** [comment]
I mean adding an extension category.

**Comment by GalacticCoderReturns** [comment]
Could someone reply to this?

**Comment by RedMan13** [comment]
no :trollface:

**Comment by Ianyourgod** [comment]
skill

**Comment by GalacticCoderReturns** [comment]
Seriously guys????????

**Comment by GalacticCoderReturns** [comment]
Jeremy answers all of the time!!!

**Comment by GalacticCoderReturns** [comment]
I'm not skilled at Javascript!!!!!!!

**Comment by FreshPenguin112** [comment]
Major skill issue 😂😂

**Comment by JeremyGamer13** [comment]
that menu is here: https://github.com/PenguinMod/penguinmod.github.io/blob/develop/src/lib/libraries/extensions/index.jsx
as for actually making an extension its a lot more complicated so i dont have a tutorial or anything

**Comment by GalacticCoderReturns** [comment]
OK. That's what I wanted to know!

**Comment by GalacticCoderReturns** [comment]
Wasn't exactly what I wanted to know.

**Comment by JoshAtticus** [comment]
Stale
