### ISSUE TITLE
Cannot upload projects on iOS

### ISSUE THREAD

**Issue by EthanRStokes** [PenguinMod/penguinmod.github.io#27]
### Expected Behavior

The file selection should look for project files

### Actual Behavior

Cannot select project files to upload, not highlighted in the files selection tool

### Steps to Reproduce

Save a project
Try to upload it

### Operating System and Browser

iOS 17.0.3 Safari 17.0.3

**Comment by EthanRStokes** [comment]
Update: Only .pm files can be uploaded for some reason

**Comment by RedMan13** [comment]
this is just ios being shitty and stupid
not much we can do about it
