### ISSUE TITLE
Make a Scratch-safe editor-only version of PenguinMod

### ISSUE THREAD

**Issue by PPPDUD** [PenguinMod/penguinmod.github.io#29]
^^ This would be really nice for a lot of scratchers who want to use the PenguinMod editor and share their projects with their friends. Perhaps it should have a different name, like AntarcticaMod, to prevent the ST from getting mad.

**Comment by JeremyGamer13** [comment]
this wouldnt be a priority if we made it, but it would likely use something like https://studio.penguinmod.com/playground.html to make it possible

**Comment by SharkPool-SP** [comment]
There's no point in this when literally you can export the project, package the project, and or upload the project to the penguinmod site
