### ISSUE TITLE
Backpack doesn't backpack code

### ISSUE THREAD

**Issue by WINRARisyou** [PenguinMod/penguinmod.github.io#32]
### Expected Behavior

The backpack should take code no problem

### Actual Behavior

The backpack area lights up but nothing happens

### Steps to Reproduce

Take any random code block and try and backpack it. It shouldn't work

### Operating System and Browser

Windows 10, Chrome and ChromeOS

https://github.com/PenguinMod/penguinmod.github.io/assets/99762912/799ba18a-4d24-4161-99b5-579e283f4a74

**Comment by WINRARisyou** [comment]
i didn't realize my mic was on sorry for the mouse click sound

**Comment by WINRARisyou** [comment]
didnt mean to close it

**Comment by RedMan13** [comment]
fixed
