### ISSUE TITLE
Using the default equals block, everything equals " "???

### ISSUE THREAD

**Issue by qtqgyt** [PenguinMod/penguinmod.github.io#34]
### Expected Behavior

It should return false with "abc =' '"

### Actual Behavior
It returns true

### Steps to Reproduce
Enter those values into a block and click on it

### Operating System and Browser
Ubuntu 22.04 LTS and Firefox 120.0

**Comment by qtqgyt** [comment]
Just some bug

**Comment by Ianyourgod** [comment]
yeah… and a bug shouldn’t be closed

**Comment by RedMan13** [comment]
i dont understand

**Comment by RedMan13** [comment]
im on the same version of ubuntu and firefox and this bug just doesnt exist i dont understand what your talking about
