### ISSUE TITLE
GPL violation

### ISSUE THREAD

**Issue by GarboMuffin** [PenguinMod/penguinmod.github.io#36]
It is obvious that this is based on https://github.com/TurboWarp/scratch-gui/ which is licensed under the GPLv3, while this repository claims to be under the MIT License - https://github.com/PenguinMod/penguinmod.github.io/blob/develop/LICENSE. This is a violation of the copyleft clauses of the GPL.

GPLv3 also applies to code taken from Scratch Addons.

**Comment by GarboMuffin** [comment]
Please also note section 8:

```
  8. Termination.

  You may not propagate or modify a covered work except as expressly
provided under this License.  Any attempt otherwise to propagate or
modify it is void, and will automatically terminate your rights under
this License (including any patent licenses granted under the third
paragraph of section 11).

  However, if you cease all violation of this License, then your
license from a particular copyright holder is reinstated (a)
provisionally, unless and until the copyright holder explicitly and
finally terminates your license, and (b) permanently, if the copyright
holder fails to notify you of the violation by some reasonable means
prior to 60 days after the cessation.

  Moreover, your license from a particular copyright holder is
reinstated permanently if the copyright holder notifies you of the
violation by some reasonable means, this is the first time you have
received notice of violation of this License (for any work) from that
copyright holder, and you cure the violation prior to 30 days after
your receipt of the notice.

  Termination of your rights under this section does not terminate the
licenses of parties who have received copies or rights from you under
this License.  If your rights have been terminated and not permanently
reinstated, you do not qualify to receive new licenses for the same
material under section 10.
```

**Comment by RedMan13** [comment]
idk what that means but coolio time to copy paste a file :bleh

**Comment by GarboMuffin** [comment]
Copying and pasting a file does not make you GPLv3 compliant. If you have no idea what you're talking about then you probably shouldn't be mocking copyright law; find someone who has at least vaguely understands.

**Comment by RedMan13** [comment]
well you seem to, so what are we in violation of and how can we fix it

**Comment by GarboMuffin** [comment]
https://github.com/PenguinMod/PenguinMod-Blocks is also in violation for the same reason

**Comment by RedMan13** [comment]
both files have been updated, is there anything else thats in violation of the licenses

**Comment by GarboMuffin** [comment]
There are online resources that you can reference to learn about the GPLv3 and copyright law. I am not your lawyer. The notable thing is that everything used by any GPLv3 repository must be open source (read the license to see what "open source" actually means). I hope you are meeting that requirement. Best of luck.
