### ISSUE TITLE
Idea: Import from Scratch Project (for editor)

### ISSUE THREAD

**Issue by Rubiidev-18** [PenguinMod/penguinmod.github.io#39]
I would like it so that in the file menu in the editor, there can be a button called import from scratch project, where you can paste in a scratch project ID, and it gets imported into penguinmod, where you can edit it, this can save people time instead of saving a project and loading the project into pm.

**Comment by JeremyGamer13** [comment]
im not sure how useful this would be since scratch doesnt let us import unshared projects

**Comment by Rubiidev-18** [comment]
> im not sure how useful this would be since scratch doesnt let us import unshared projects

it wouldn't do unshared though, forgot to add that to the idea.

**Comment by RedMan13** [comment]
unless you mean like, explicitly by id, this is already an option, you just have to select "scratch project" when selecting what file type to search for in the file selector

**Comment by RedMan13** [comment]
just save to pc and load into the editor :trollface:

**Comment by Rubiidev-18** [comment]
> just save to pc and load into the editor :trollface:

it would be quicker than doing that like what I said in the idea.

**Comment by Ianyourgod** [comment]
no. this promotes just posting other people’s scratch projects.

**Comment by Rubiidev-18** [comment]
> no. this promotes just posting other people’s scratch projects.

yea, guess that's sorta true, closed.
