### ISSUE TITLE
Changing the editor title to the project name

### ISSUE THREAD

**Issue by mariocraft987** [PenguinMod/penguinmod.github.io#40]
You should make it when the project name is `onkeyclicked` event then change the title in javascript using `document.title = projectName + " on penguinmod"` then have a project name in the document title like scratch!

**Comment by JeremyGamer13** [comment]
the editor already does this?

**Comment by RedMan13** [comment]
> the editor already does this?

no?

**Comment by RedMan13** [comment]
it displays as `PenguinMod - Editor` even when viewing a project

**Comment by JeremyGamer13** [comment]
> it displays as `PenguinMod - Editor` even when viewing a project

![image](https://github.com/PenguinMod/penguinmod.github.io/assets/69337718/cc7dee04-e90a-4b55-8889-504746f9469f)

**Comment by JeremyGamer13** [comment]
![image](https://github.com/PenguinMod/penguinmod.github.io/assets/69337718/93c58020-a003-43de-800e-aac52ce3342d)
you dont even need to be on an uploaded project either

**Comment by RedMan13** [comment]
huh, must have changed recently, cause it hasnt done that at all last i was messing with it

**Comment by Mariocraft987** [comment]
oh

**Comment by mariocraft987** [comment]
Oh!
