### ISSUE TITLE
Small mistake in credits

### ISSUE THREAD

**Issue by Xeltalliv** [PenguinMod/penguinmod.github.io#49]
![image](https://github.com/PenguinMod/penguinmod.github.io/assets/90340988/bbc2940b-1286-4b76-b71e-009195593998)

https://github.com/PenguinMod/penguinmod.github.io/blob/5f261e84499f5191b67f4bf842a2d6d0bd17a036/src/playground/credits/users.js#L344-L351
My scratch username is Vadik1.
My github username is Xeltalliv.
Github user Vadik1 is unrelated

**Comment by Ianyourgod** [comment]
if i have time i’ll fix that in like an hour

**Comment by JeremyGamer13** [comment]
made a commit to fix this now
