### ISSUE TITLE
The game crashes> "Unknow attachment type"

### ISSUE THREAD

**Issue by Pispowispo333** [PenguinMod/penguinmod.github.io#56]
### Expected Behavior
The game should run normally

_Please describe what should happen_
When you were playing the game for a long time you should keep playing normally
### Actual Behavior

_Describe what actually happens_
The game crashes in a white screen

### Steps to Reproduce
Play the game for a few minuts

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_
literally just open the game and play for a few minuts.

### Operating System and Browser
windows Opera GX

**Comment by Ianyourgod** [comment]
what game????

**Comment by RedMan13** [comment]
yeah what game

**Comment by Pispowispo333** [comment]
one who I created on penguinmod

**Comment by Pispowispo333** [comment]
wen you play it for a few minuts it crashes and says ¨Unknown attachement type¨

**Comment by RedMan13** [comment]
still dont know what game uour talking about

**Comment by Ianyourgod** [comment]
> one who I created on penguinmod

 could you send it… we don’t have the game… only you do…

**Comment by Pispowispo333** [comment]
ok I´ll do its, sorry, I didn´t know you needed the game

**Comment by Pispowispo333** [comment]
well, I only can send it in a long way, this may take long

**Comment by Pispowispo333** [comment]
I cant send it, there isn´t another way to help me, here you have a screenshot of the console when the issue happens
![Uploading Captura de pantalla (596).png…]()

**Comment by Ianyourgod** [comment]
that is just a link back to this page.

**Comment by RedMan13** [comment]
you didnt wait for the image to upload so we dont actually have the photo

**Comment by lego7set** [comment]
https://discord.com/channels/1033551490331197462/1236086867305173074

the discord thread for this thingy

**Comment by Pispowispo333** [comment]
what, ok sorry i will send it again 
![Captura de pantalla (597)](https://github.com/PenguinMod/penguinmod.github.io/assets/142848519/25be629f-872e-48be-8da5-43f3f9ed9a9d)

**Comment by polygoners1** [comment]
its probaly because you have 26 extensions, over 120 sprites and 10621 blocks.

**Comment by Ianyourgod** [comment]
no, that should cause bugs, just slow down the page.

**Comment by RedMan13** [comment]
> no, that should cause bugs, just slow down the page.

but he still isnt wrong just beacuse of shear human error

the idea with that being, it is next to impossible to actually just know what is wrong because there is so much to check and no pointers for what yhe check

**Comment by RedMan13** [comment]
oh yeah this was possibly solved in the discord? idk the poster just kinda ended the conversation...
