### ISSUE TITLE
PenguinGPT how can use extension 

### ISSUE THREAD

**Issue by ErNisha4800** [PenguinMod/penguinmod.github.io#59]
### Expected Behavior

_Please describe what should happen_

### Actual Behavior

_Describe what actually happens_

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by Ianyourgod** [comment]
the extension creators servers are off and he’s not planning on fixing it. we cant do anything about it, and so the extension is basically permanently broken
