### ISSUE TITLE
just showcasing a project.

### ISSUE THREAD

**Issue by polygoners1** [PenguinMod/penguinmod.github.io#61]
the project is here!
it is a macro recorder and player.
[macro recorder stuff.zip](https://github.com/PenguinMod/penguinmod.github.io/files/15370253/macro.recorder.stuff.zip)

**Comment by polygoners1** [comment]
also im using this because i cant use the pmp or zip on the forums.

**Comment by polygoners1** [comment]
yeah closed because its not a problem or bug showcase project.

**Comment by polygoners1** [comment]
wait it will get more views if the issue is open

**Comment by SharkPool-SP** [comment]
Stop

**Comment by JeremyGamer13** [comment]
sorry but issues are not a place for project sharing
