### ISSUE TITLE
no website?

### ISSUE THREAD

**Issue by GoldySlimepup** [PenguinMod/penguinmod.github.io#62]
### Expected Behavior

the website for this mod

### Actual Behavior

you made a website for this mod

### Steps to Reproduce

yea i want to test it out

### Operating System and Browser

_e.g. Windows 11 Opera_

**Comment by JeremyGamer13** [comment]
whajt

**Comment by GoldySlimepup** [comment]
wait i thought i was in a another mod, srry

**Comment by Steve0Greatness** [comment]
Could you close this?
