### ISSUE TITLE
Render freaks out when fullscreening

### ISSUE THREAD

**Issue by badu888** [PenguinMod/penguinmod.github.io#70]
### Expected Behavior

Render correctly in both nomal and fullscreen modes

### Actual Behavior

Renders everything as black square

### Steps to Reproduce

It happens for me when entering fullscreen mode, maybe that's how to reproduce this glitch
Video:

https://github.com/user-attachments/assets/c97046e8-44d7-4ed6-95cd-903c6dcc94e5

(it also happened when i started project after importing it)

### Operating System and Browser

Windows 10 22H2 Russian 64bit
Chrome 127.0.6533.120 64bit

**Comment by SharkPool-SP** [comment]
invalid, we're testing a new renderer feature at the moment, thats just it being turned on when its not supposed to

**Comment by badu888** [comment]
ok

**Comment by badu888** [comment]
seems like renderer is now ok

**Comment by SharkPool-SP** [comment]
cuz I fixed it 💀

**Comment by badu888** [comment]
(OFFLINE)

**Comment by badu888** [comment]
:trollface:
