### ISSUE TITLE
wtf is ths error

### ISSUE THREAD

**Issue by hammouda101010** [PenguinMod/penguinmod.github.io#71]
### Expected Behavior

this line of code (including brodcasts) shoud work every time:
![block_8_26_2024-6_47_51 PM](https://github.com/user-attachments/assets/f9150445-642c-4ea9-ae63-e85991652ea1)

### Actual Behavior

 instead it shows this error: TypeError: Cannot read properties of undefined (reading 'SPifThread')

### Steps to Reproduce

link to project(dont forget to unzip) :
[silly.zip](https://github.com/user-attachments/files/16754506/silly.zip)

### Operating System and Browser

_Windows 11 Microsoft Edge 128.0.2739.42 (Official build) (64-bit) _

**Comment by SharkPool-SP** [comment]
thats my extensions' fault, working on the fix at the moment

**Comment by hammouda101010** [comment]
> thats my extensions' fault, working on the fix at the moment

you fixed it, right?

**Comment by SharkPool-SP** [comment]
just fixed it now, give it a few minutes then reload the page and project, it should work fine

**Comment by hammouda101010** [comment]
btw what extension caused the error

**Comment by hammouda101010** [comment]
and alse wth its this error: setPrivateSkinAccess

**Comment by RedMan13** [comment]
that's not an error that's the name of a function that couldn't be found

**Comment by SharkPool-SP** [comment]
> btw what extension caused the error

doesnt matter, its fixed :trollface:

**Comment by hammouda101010** [comment]
![block_8_26_2024-8_01_22 PM](https://github.com/user-attachments/assets/7c47d337-2f70-48ad-8743-30899bbaec2d)
apparently, its this stupid little block that caused the bug

**Comment by hammouda101010** [comment]
and lilys more events extensions

**Comment by SharkPool-SP** [comment]
> and lilys more events extensions

nope :trollface:

**Comment by hammouda101010** [comment]
its stil broken idk why

**Comment by hammouda101010** [comment]
btw here is the file again, for those whowants to find the bug in thre project, cuz i suck at finding bugs

**Comment by hammouda101010** [comment]
[silly.zip](https://github.com/user-attachments/files/16768435/silly.zip)

**Comment by SharkPool-SP** [comment]
> its stil broken idk why

Which one, the skinPrivateacess one?

**Comment by hammouda101010** [comment]
nvm, i found the bug: its an infinite loop that caused the error. but i put an stop script so now it works fine.
