### ISSUE TITLE
(Question) What is The Lore and Origins for Each Custom Penguinmod Sprites?

### ISSUE THREAD

**Issue by hammouda101010** [PenguinMod/penguinmod.github.io#72]

**Comment by RedMan13** [comment]
none
although ig if you take my memey project uploaded to the test server as a canon then theres an incredibly small amount for pang and the crabs

**Comment by hammouda101010** [comment]
who are the crabs

**Comment by hammouda101010** [comment]
and choci? and joe? and aae? who made these sprites?

**Comment by RedMan13** [comment]
everyone who has added a sprite is listed in the credits, all new sprites currently are from the discord (and realistically literally every single asset ever added can be traced back to somewhere in the discord server)

**Comment by hammouda101010** [comment]
ok but can you show the creators of each sprites i mentioned

**Comment by RedMan13** [comment]
> who are the crabs

https://projects.penguinmod.com/4813070144

**Comment by hammouda101010** [comment]
> > who are the crabs
> 
> https://projects.penguinmod.com/4813070144

most cursed crap i ever seen

**Comment by hammouda101010** [comment]
> ok but can you show the creators of each sprites i mentioned

hello, hello?

**Comment by RedMan13** [comment]
> > > who are the crabs
> > 
> > 
> > https://projects.penguinmod.com/4813070144
> 
> most cursed crap i ever seen

how dare you insult my master pice 💢

**Comment by RedMan13** [comment]
> ok but can you show the creators of each sprites i mentioned

no too lazy
i know aea is by jeremy 🥱

**Comment by RedMan13** [comment]
actually no too lazy for xhocci, i know who but i wouldhae to look rhem up on discord to actually give yu rhe flcreator
joe is by joe (puzzlingggg)

**Comment by RedMan13** [comment]
and ddededodediamante is by genix for ddededodediamante

**Comment by hammouda101010** [comment]
> > ok but can you show the creators of each sprites i mentioned
> 
> no too lazy i know aea is by jeremy 🥱

do it, or i will kidnapp you in my basment.

**Comment by derpygamer2142** [comment]
joe was made by puzzlingggg, choci was made by concertaylis

**Comment by hammouda101010** [comment]
> actually no too lazy for xhocci, i know who but i wouldhae to look rhem up on discord to actually give yu rhe flcreator joe is by joe (puzzlingggg)

lot of grammar errors

**Comment by RedMan13** [comment]
idotn calre you caed my projectcrlap >:((((((((((((((((((((((((((((((((((((((

**Comment by RedMan13** [comment]
> > > ok but can you show the creators of each sprites i mentioned
> > 
> > 
> > no too lazy i know aea is by jeremy 🥱
> 
> do it, or i will kidnapp you in my basment.

i don care im already in jeremys

**Comment by hammouda101010** [comment]
> idotn calre you caed my projectcrlap >:((((((((((((((((((((((((((((((((((((((

acctualy its a national treasure sorry for saying its crap.

**Comment by hammouda101010** [comment]
> > idotn calre you caed my projectcrlap >:((((((((((((((((((((((((((((((((((((((
> 
> acctualy its a national treasure sorry for saying its crap.

also you kind of leaked the new penginmod server 🤣 🤣 🤣 :trollface:

**Comment by JeremyGamer13** [comment]
its in public beta now
