### ISSUE TITLE
Turbobuilder: Input not showing.

### ISSUE THREAD

**Issue by hammouda101010** [PenguinMod/penguinmod.github.io#73]
### The Broken Block:
![Screenshot 2024-09-05 162904](https://github.com/user-attachments/assets/1a8f6ed4-8b3d-4c7a-a5e7-a9aab25e1fbb)

### Expected Behavior

it _**should**_ show an input:
![scratchblocks](https://github.com/user-attachments/assets/e5f0b73e-cec1-42b2-b724-f1d67cf4289d)

### Actual Behavior

it shows **_nothing_** instead, same for reporters and boolean blocks:
![block_9_5_2024-4_33_33 PM](https://github.com/user-attachments/assets/438c4276-b448-4622-9849-54778cffd171)

### Steps to Reproduce

create a block like **this**:
![Screenshot 2024-09-05 163447](https://github.com/user-attachments/assets/5f256564-52ad-4d56-9536-de66e0208c80)

then import the Turbobuilder extension like this:
![Screenshot 2024-09-05 163917](https://github.com/user-attachments/assets/bdebc5dd-c5aa-4dfe-bdeb-e99f2c93ea2a)

### Operating System and Browser

_Windows 10, Microsoft Edge_

**Comment by RedMan13** [comment]
turbobuilder issues should go to turbobuilder, NOT penguinmod

**Comment by jwklong** [comment]
this is not related to penguinmod, turbobuilder is a separate project.

also your meant to put `[ID]` in the block text

**Comment by hammouda101010** [comment]
there is no way to report an issue to turbobuilder (atleast jwklong's fork) and how am i supposed to know this

**Comment by RedMan13** [comment]
> there is no way to report an issue to turbobuilder (atleast jwklong's fork) and how am i supposed to know this

go to the turbo builder repo and report it 💀
and dont ask me where, github search exists for a damn reason and jwklong is literally right here talking to you righr now 💀

**Comment by hammouda101010** [comment]
> this is not related to penguinmod, turbobuilder is a separate project.
> 
> also your meant to put `[ID]` in the block text

how do i make a block menu
