### ISSUE TITLE
[BUG] When loading save it only accepts .pm

### ISSUE THREAD

**Issue by macohi** [PenguinMod/penguinmod.github.io#74]
### Expected Behavior

accepts .sb3, .sb2, .pm, and .pmp like the code suggests

### Actual Behavior

accepts only .pm (but saves .pmp?)

### Steps to Reproduce

1) save project (.pmp)
2) create new project
3) try to load project (.pmp)
4) fail
5) rename .pmp to .pm
6) load project
7) works.

### Operating System and Browser

IpadOS 17.6.1 and Safari

**Comment by RedMan13** [comment]
we cant handle bugs with apple systems at all

**Comment by macohi** [comment]
oh
