### ISSUE TITLE
Snapping line in costume editor is unusually short

### ISSUE THREAD

**Issue by BlueTheCube** [PenguinMod/penguinmod.github.io#75]
### Expected Behavior

The line should extend as long as the the page

### Actual Behavior

The line doesn't extend fully and appears unusually short
![Screenshot 2024-09-17 102626](https://github.com/user-attachments/assets/4323d773-2a09-4c1b-b158-769212c6538e)

### Steps to Reproduce

Enable costume editor snapping and set stage to widescreen, then drag something in the costume editor

### Operating System and Browser

Windows 11 and Chrome

**Comment by RedMan13** [comment]
image pls

**Comment by BlueTheCube** [comment]
@RedMan13 already did
![Screenshot 2024-09-17 102626](https://github.com/user-attachments/assets/be9fd89f-9dff-4582-b014-01d3a3a5c65a)

**Comment by RedMan13** [comment]
oh ot never showed

**Comment by RedMan13** [comment]
how the hell is the line off center

**Comment by BlueTheCube** [comment]
i do not know either
can you update the old snap line to something similar to turbowarp's snap line

**Comment by BlueTheCube** [comment]
set your aspect ratio 16:9
![Screenshot 2024-09-18 170742](https://github.com/user-attachments/assets/fa9b468b-d50a-40b0-9791-bf435cdc8d7e)

**Comment by MerrCraft** [comment]
maybe that put a off-center thing in the css.

**Comment by RedMan13** [comment]
what! css? in my canvas! this is impossible!!!

**Comment by PuzzlingGGG** [comment]
yea snapping literally only works for 4:3 ro whatever

**Comment by MerrCraft** [comment]
> what! css? in my canvas! this is impossible!!!

CSS, cascading style file, look it up

**Comment by MerrCraft** [comment]
> yea snapping literally only works for 4:3 ro whatever

They gotta update that code

**Comment by jwklong** [comment]
> > what! css? in my canvas! this is impossible!!!
> 
> CSS, cascading style file, look it up

bro,,,,, its a canvas,,,,

**Comment by BlueTheCube** [comment]
it was never fixed

**Comment by PuzzlingGGG** [comment]
This addon does not work with any other size

**Comment by MerrCraft** [comment]
> This addon does not work with any other size

They could fix in css with width:100%

**Comment by RedMan13** [comment]
fixed

**Comment by RedMan13** [comment]
> > This addon does not work with any other size
> 
> They could fix in css with width:100%

literally not fucking true :skull:
