### ISSUE TITLE
Created Unofficial PenguinMod Unpackager

### ISSUE THREAD

**Issue by hammouda101010** [PenguinMod/penguinmod.github.io#76]
https://github.com/hammouda101010/PenguinModUnofficialUnpackager 
link to repo (low effort, forked from turbowarp's unpackager.)

**Comment by Ianyourgod** [comment]
there is already a packager.

**Comment by hammouda101010** [comment]
> there is already a packager.

actually, its an unpackager, there was an error in the title

**Comment by Ianyourgod** [comment]
the turbowarp one works with penguinmod.

**Comment by hammouda101010** [comment]
it still shortens the step to change the file's extension. so its made for penguinmod. but can also works with turbowarp, but it only outputs a .pmp file.

**Comment by RedMan13** [comment]
> it still shortens the step to change the file's extension. so its made for penguinmod. but can also works with turbowarp, but it only outputs a .pmp file.

you dont need to, you can just change the file type filter when it prompts you for a file

**Comment by RedMan13** [comment]
thats what the deopdownthat says ".sb3" or what ever is

**Comment by hammouda101010** [comment]
> thats what the deopdownthat says ".sb3" or what ever is

idk why you didnt made your own unpackager

**Comment by RedMan13** [comment]
because tou can just use turbowarps

**Comment by hammouda101010** [comment]
> because tou can just use turbowarps

at this point its just a worthless debate, i dont give a #### to this anymore

**Comment by Ianyourgod** [comment]
don’t worry we don’t either ❤️❤️

**Comment by hammouda101010** [comment]
> don’t worry we don’t either ❤️❤️

also there is a problem with toast notifs extension. hope MubiLop FIx This Issue. or you update your extensions list please thank you ❤️❤️❤️

**Comment by cicerorph** [comment]
> > don’t worry we don’t either ❤️❤️
> 
> also there is a problem with toast notifs extension. hope MubiLop FIx This Issue. or you update your extensions list please thank you ❤️❤️❤️

It's fixed, thank you for reporting it! (And no i'm not adding hearts to my comment)

**Comment by tellmehey** [comment]
L mubilop
