### ISSUE TITLE
status

### ISSUE THREAD

**Issue by webbrowser11** [PenguinMod/penguinmod.github.io#83]
do you think the status:
https://status.penguinmod.com/

is due to you guys fixing the server finally and everyone getting super excited?

**Comment by JeremyGamer13** [comment]
well its been a while since the inital surge of people & projects, its down again now because of a new botting issue

**Comment by webbrowser11** [comment]
oh

**Comment by Ianyourgod** [comment]
its because we were getting botted and so im adding captcha - we just have it down so we dont get another 5000 botted users

**Comment by webbrowser11** [comment]
dang will it be fixed tommorow? and will that be the first time penguin mod is up in almost a year and a half?????

**Comment by embinmc** [comment]
> dang will it be fixed tommorow? and will that be the first time penguin mod is up in almost a year and a half?????

it was up yesterday 💀 and its not been a year since the servers were originally turned off

**Comment by webbrowser11** [comment]
every single time i have gotten on in the past 18 months it was OFF even if im wrong the servers have still been patchy or down fully most of the time, i know it was up yesterday and that is why i opened this issue.

**Comment by webbrowser11** [comment]
i prob explained that bad but whatev
